### ISSUE TITLE
problem when connecting

### ISSUE THREAD

**Issue by RGdevz** [warren-bank/Android-RTSP-ScreenCaster#1]
hey im trying to test the app but when i connect i get this error

`I/RtspServer: Connection from 10.0.0.6
E/RtspServer: OPTIONS rtsp://10.0.0.16:6554
D/RtspServer: RTSP/1.0 200 OK
    Server: ScreenCaster RTSP Server
    Cseq: 2
    Content-Length: 0
    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
E/RtspServer: DESCRIBE rtsp://10.0.0.16:6554
D/AACStream: AAC supported on this phone
I/H264Stream: Testing H264 support... Test file saved at: /data/user/0/com.github.warren_bank.rtsp_screencaster/cache/spydroid-test.mp4
I/MediaRecorderJNI: setup
I/MediaRecorderJNI: setVideoSource(2)
I/MediaRecorderJNI: setVideoEncoder(2)
I/MediaRecorderJNI: setVideoSize(1080, 1920)
    setVideoFrameRate(60)
I/MediaRecorderJNI: setParameter()
I/MediaRecorderJNI: setMaxDuration(3000)
I/MediaRecorderJNI: setOutputFile
I/MediaRecorderJNI: prepare
I/MediaRecorderJNI: finalize
    release
I/MediaRecorderJNI: finalize
    release
I/MediaRecorderJNI: stop
E/MediaRecorder: stop called in an invalid state: 8
I/MediaRecorderJNI: release
E/RtspServer: Attempt to invoke virtual method 'void android.hardware.display.VirtualDisplay.release()' on a null object reference
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.display.VirtualDisplay.release()' on a null object reference
        at net.majorkernelpanic.screening.video.H264Stream.testMediaRecorderAPI(H264Stream.java:223)
        at net.majorkernelpanic.screening.video.H264Stream.testH264(H264Stream.java:117)
W/System.err:     at net.majorkernelpanic.screening.video.H264Stream.updateMP4Config(H264Stream.java:103)
        at net.majorkernelpanic.screening.video.H264Stream.configure(H264Stream.java:99)
        at net.majorkernelpanic.screening.Session.syncConfigure(Session.java:326)
W/System.err:     at net.majorkernelpanic.screening.rtsp.RtspServer$WorkerThread.processRequest(RtspServer.java:451)
        at net.majorkernelpanic.screening.rtsp.RtspServer$WorkerThread.run(RtspServer.java:396)
D/RtspServer: RTSP/1.0 500 Internal Server Error
    Server: ScreenCaster RTSP Server
    Cseq: 3
    Content-Length: 0
I/RtspServer: Client disconnected
`

cant really figure out what not working here please help

**Comment by warren-bank** [comment]
Hi. At the moment, I'm too busy to spend much time digging into this.

Off-hand questions:
* does your phone meet the minimum requirements to run the server?
  - Android 5.0+
* what client are you using to connect to the server?
  - I've only successfully tested with VLC and ffmpeg (ffplay)
  - I've seen other clients have problems (ex: [ExoPlayer](https://github.com/google/ExoPlayer/pull/3854#issuecomment-720048344))

Off-hand suggestions:
* run your tests again using an unmodified libstreaming server (which uses the camera, rather than the screen)
  - [official examples repo](https://github.com/fyhertz/libstreaming-examples)
  - [my unofficial examples repo](https://github.com/warren-bank/Android-libraries/tree/fyhertz/libstreaming-examples)
  - [my unofficial apk builds](https://github.com/warren-bank/Android-libraries/releases/tag/fyhertz%2Flibstreaming-examples%2Fv01.00.00)
    * [example 1](https://github.com/warren-bank/Android-libraries/releases/download/fyhertz%2Flibstreaming-examples%2Fv01.00.00/example1-release.apk) is the relevant app to test
* if you encounter the same problem, then the issue involves the upstream library.. which I modified, but only slightly.
* if that works, then it's something I did..

**Comment by RGdevz** [comment]
hey thanks for replying 

I tried it on my phone (glaxay s7 which have android 7) and with emulator with android 11 and got the same problem in both

I tried the original libstreaming lib and its works fine I'm not surewhat not working but I think the mediarecoder is falling to start for some reason but I'm not really a expert in this stuff to know

I found other library which works that not using the mediarecoder but using mediacodec 
[https://github.com/306470558/Android_show_screen_rtsp](url) 

and its work fine after I used some code from your lib in the H264Packetizer

**Comment by warren-bank** [comment]
impressive googling skills :smiley: ..I somehow missed that [app](https://github.com/306470558/Android_show_screen_rtsp) when I looked.. ie, before going down the path of trying to write one.

When I have some time, I'll definitely take a look at their code.. and hopefully borrow some ideas.. to make this app more robust.

**Comment by RGdevz** [comment]
glad to hear thank for the help 👍
